name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master
env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: docker-pyinstaller

jobs:
  build_linux_py2:
    env:
      IMAGE_TAG: linux_py2
      DOCKERFILE_PATH: linux/py2/
    
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2
      - name: Image Naming
        run: |
          IMAGE_ID=docker.pkg.github.com/${{ github.repository }}/$IMAGE_NAME
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          echo "IMAGE_ID=$IMAGE_ID" >> $GITHUB_ENV

      - name: Build image
        run: docker build -t $IMAGE_NAME:$IMAGE_TAG $DOCKERFILE_PATH

      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: |
          echo "$IMAGE_ID:$IMAGE_TAG"
          docker push $IMAGE_ID:$IMAGE_TAG
